### PR TITLE
exec_cmdline implementation + small fixes

### LINKED ISSUE #2494: [Linux / Fedora][DeadBeeF 1.8.4] Local file mask not respected for album art
### Steps to reproduce the problem

When I play a file where there should be no artwork, DeaDBeeF picks a random JPG file in the same folder.

The pattern is set to: `*cover*.jpg;*front*.jpg;*folder*.jpg;*cover*.png;*front*.png;*folder*.png`

The file name of the pictures picked don't respect this mask (`mpv-shot0002.jpg`, `62423173-7736d800-b6f0-11e9-9ddd-e48832259695.jpg`).

### Information about the software:

DeadBeeF version: 1.8.4
OS: Fedora 32

### PR DESCRIPTION
**Pull request by kuba160**
Fixes:
- Add premake build files into `.gitignore`
- Fix hardcoded wildcards in `artwork-legacy` (fixes #2494)

exec_cmdline:
- Runs in `server_exec_command_line`
- Gets plugins from `plug_get_list()` and calls `exec_cmdline` if implemented
- Calls every plugin even though some plugin might already have used and processed given arguments. I was unsure what 'right' behavior should be. There might be a case where some broken plugin can pretend to have used arguments and make other plugins not receive `exec_cmdline` calls. From other side this can lead to arguments being interpreted twice. Can change depending on your final opinion.

EDIT:
Proposal of implementation can be found here: https://gist.github.com/Alexey-Yakovenko/aa226803af604042721d671ecde94c3d

### CODE REVIEW

File: main.c [hunk 1]
```diff
@@ -377,6 +377,71 @@ server_exec_command_line (const char *cmdline, int len, char *sendback, int sbsi
...
+                        FILE *fp = tmpfile();
+                        if (!fp) {
+                            trace_err ("Creating tmpfile failed: %s\n", strerror(errno));
+                            return -1;
+                        }
+                        int fd = fileno (fp);
+                        int plugarg_len = (int)(parg_len - strlen(parg) - 1);
+                        int ret = plugins[i]->exec_cmdline(parg + strlen(parg) + 1, plugarg_len, fd);
+                        // copy plugin output to sendback
+                        if (lseek(fd, 0, SEEK_CUR) && sendback) {
```
Comment (kuba160) [inline main.c:411]: This should use SEEK_END instead of SEEK_CUR

File: main.c [hunk 2]
```diff
@@ -377,6 +380,80 @@ server_exec_command_line (const char *cmdline, int len, char *sendback, int sbsi
...
+                }
+                parg_len += strlen(parg + parg_len) + 1;
+            }
+            parg_len--;
+
+            const char *plugid = parg + strlen("--plugin=");
+            DB_plugin_t ** plugins = plug_get_list();
+            int i = 0;
+            while (plugins[i]) {
+                if (strcmp(plugins[i]->id, plugid) == 0) {
```
Comment (Alexey-Yakovenko) [inline main.c:403]: Please use `plug_get_for_id` instead

**Review by Alexey-Yakovenko — CHANGES_REQUESTED** [review]

**Comment by kuba160** [comment]
I'll test the changes tomorrow. After that I'm gonna squash all commits related to `exec_cmdline` into one. I also noticed that api version history is wrong in `deadbeef.h` - it says that API 1.13 is for deadbeef 1.9 and we are already on 1.15 🙂.

**Comment by Alexey-Yakovenko** [comment]
> I also noticed that api version history is wrong in deadbeef.h - it says that API 1.13 is for deadbeef 1.9 and we are already on 1.15 🙂.

I noticed that too, it's already corrected on medialib branch. There's no need to change it on master right now.

**Comment by kuba160** [comment]
I tested the implementation and applied small adjustments. All commits related to `exec_cmdline` have been merged into one. The original branch can be found here: https://github.com/DeaDBeeF-for-Windows/deadbeef/tree/cmdline

Example implementation of `exec_cmdline` can be found here (plugin cust_seek, branch cmdline): https://github.com/kuba160/ddb_cust_seek/blob/83724e08cb24b8f7adbce240a857c404bce04ab2/cust_seek.c#L142

**Comment by Alexey-Yakovenko** [comment]
@kuba160 
Please note: I don't guarantee that the API will stay unchanged in the next release. I'll notify you about any changes, as necessary.
